// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isSupabaseConfigured, supabaseCredentials } from './config';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export { isSupabaseConfigured } from './config';

export const supabase = createClient<Database>(
  supabaseCredentials.url,
  supabaseCredentials.key,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
