// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isSupabaseConfigured, supabaseCredentials } from './config';

type SupabaseWithStatus = SupabaseClient<Database> & { __disabled?: boolean };

const disabledResult = (action: string) => ({
  data: null,
  error: new Error(
    `Supabase authentication is unavailable. ${action} cannot be completed until environment variables are configured.`,
  ),
});

const createDisabledQueryBuilder = () => {
  const resultPromise = Promise.resolve(disabledResult("Database query"));

  const builder: any = {
    then: resultPromise.then.bind(resultPromise),
    catch: resultPromise.catch.bind(resultPromise),
    finally: resultPromise.finally.bind(resultPromise),
  };

  const chainableMethods = [
    "select",
    "insert",
    "update",
    "delete",
    "eq",
    "order",
    "limit",
    "single",
    "maybeSingle",
    "returns",
  ];

  for (const method of chainableMethods) {
    builder[method] = () => builder;
  }

  return builder;
};

const createDisabledStorageBuilder = () => {
  const resultPromise = Promise.resolve(disabledResult("Storage operation"));
  const builder: any = {
    then: resultPromise.then.bind(resultPromise),
    catch: resultPromise.catch.bind(resultPromise),
    finally: resultPromise.finally.bind(resultPromise),
  };

  const chainableMethods = ["upload", "remove", "getPublicUrl"];
  for (const method of chainableMethods) {
    builder[method] = () => builder;
  }

  return builder;
};

const createDisabledSupabaseClient = (): SupabaseWithStatus => {
  const subscription = { unsubscribe: () => {} };

  return {
    auth: {
      getSession: async () => ({ data: { session: null }, ...disabledResult("Session lookup") }),
      onAuthStateChange: () => ({ data: { subscription }, ...disabledResult("Auth state listener") }),
      signInWithPassword: async () => disabledResult("Password sign-in"),
      signInWithOAuth: async () => disabledResult("OAuth sign-in"),
      signUp: async () => disabledResult("Sign-up"),
      resetPasswordForEmail: async () => disabledResult("Password reset"),
      updateUser: async () => disabledResult("Profile update"),
      resend: async () => disabledResult("Email verification"),
      signOut: async () => disabledResult("Sign out"),
      getUser: async () => ({ data: { user: null }, ...disabledResult("User lookup") }),
    },
    from: () => createDisabledQueryBuilder(),
    storage: {
      from: () => createDisabledStorageBuilder(),
    },
    __disabled: true,
  } as unknown as SupabaseWithStatus;
};

let cachedClient: SupabaseWithStatus | null = null;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export { isSupabaseConfigured } from './config';

export const getSupabaseClient = (): SupabaseWithStatus => {
  if (cachedClient) return cachedClient;

  if (!isSupabaseConfigured) {
    cachedClient = createDisabledSupabaseClient();
    return cachedClient;
  }

  if (typeof window === "undefined") {
    cachedClient = createDisabledSupabaseClient();
    return cachedClient;
  }

  try {
    cachedClient = createClient<Database>(
      supabaseCredentials.url,
      supabaseCredentials.key,
      {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        }
      }
    );
    return cachedClient;
  } catch (error) {
    console.error("Failed to initialize Supabase client", error);
    cachedClient = createDisabledSupabaseClient();
    return cachedClient;
  }
};

export const supabase = new Proxy(createDisabledSupabaseClient(), {
  get(_target, prop, receiver) {
    const client = getSupabaseClient();
    const value = Reflect.get(client, prop, receiver);

    if (typeof value === "function") {
      return value.bind(client);
    }

    return value;
  },
});
